{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import mysql.connector as sql\n",
    "import os\n",
    "import sys\n",
    "import multiprocessing as mp\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 999 µs, sys: 486 µs, total: 1.48 ms\n",
      "Wall time: 843 µs\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "['/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/FEBRERO 2022.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/MARZO 2022.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/OCTUBRE 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/ABRIL 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/ABRIL 2022.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/JUNIO 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/ENERO 2022.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/DICIEMBRE 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/MAYO 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/NOVIEMBRE 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/AGOSTO 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/SEPTIEMBRE 2021.csv',\n",
       " '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV/JULIO 2021.csv']"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%time\n",
    "ruta = '/home/dmateons/Documents/mateo/python/Parallel_Concurrent/data/CSV'\n",
    "files_list = os.listdir(ruta)\n",
    "file_list = [f\"{ruta}/{filename}\" for filename in files_list if filename.endswith('.csv')]\n",
    "file_list\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 14.7 s, sys: 3.68 s, total: 18.4 s\n",
      "Wall time: 3.56 s\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "19449625"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%time\n",
    "registros = 0\n",
    "for file in files_list:\n",
    "    df = pd.read_csv(file_list[0], engine='pyarrow')\n",
    "    registros += df.shape[0]\n",
    "    \n",
    "registros"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df.drop(['VELOCIDAD', 'ID'], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1496125 entries, 0 to 1496124\n",
      "Data columns (total 8 columns):\n",
      " #   Column     Non-Null Count    Dtype         \n",
      "---  ------     --------------    -----         \n",
      " 0   DATE_TIME  1496125 non-null  datetime64[ns]\n",
      " 1   LATITUDE   1493010 non-null  float64       \n",
      " 2   LONGITUDE  1493010 non-null  float64       \n",
      " 3   ADDRESS    1496125 non-null  object        \n",
      " 4   SPEED      1492508 non-null  float64       \n",
      " 5   MILEAGE    1189306 non-null  float64       \n",
      " 6   IGNICION   1334641 non-null  float64       \n",
      " 7   PLACA      1496125 non-null  object        \n",
      "dtypes: datetime64[ns](1), float64(5), object(2)\n",
      "memory usage: 91.3+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1496125, 8)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "query_create_table ='''\n",
    "CREATE TABLE rastreo_satelital_v2 (\n",
    "    ID INT auto_increment,\n",
    "    DATE_TIME DATETIME NULL,\n",
    "    LATITUDE DOUBLE NULL,\n",
    "    LONGITUDE DOUBLE NULL,\n",
    "    ADDRESS VARCHAR(500) NULL,\n",
    "    SPEED INT NULL,\n",
    "    MILEAGE FLOAT NULL,\n",
    "    IGNICION INT NULL,\n",
    "    PLACA VARCHAR(10) NULL,\n",
    "    constraint rastreo_satelital_v2_pk\n",
    "        primary key (ID)\n",
    ")\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymysql.cursors\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "HOST = os.getenv('HOST')\n",
    "USER = os.getenv('USERDB')\n",
    "PASS = os.getenv('PASSDB_LOCAL')\n",
    "DB = os.getenv('DATABASE')\n",
    "\n",
    "\n",
    "connection = pymysql.connect(host=\"35.239.212.126\",\n",
    "                             user=USER,\n",
    "                             password=PASS,\n",
    "                             database=DB)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(('rastreo_satelital',), ('rastreo_satelital_v2',))\n"
     ]
    }
   ],
   "source": [
    "cursor = connection.cursor()\n",
    "sql = \"SHOW TABLES\"\n",
    "cursor.execute(sql)\n",
    "result = cursor.fetchall()\n",
    "print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(('rastreo_satelital',), ('rastreo_satelital_v2',))\n",
      "CPU times: user 1.77 ms, sys: 330 µs, total: 2.1 ms\n",
      "Wall time: 208 ms\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "cursor.execute(query_create_table)\n",
    "result = cursor.fetchone()\n",
    "\n",
    "sql = \"SHOW TABLES\"\n",
    "cursor.execute(sql)\n",
    "result = cursor.fetchall()\n",
    "print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['ODBC Driver 18 for SQL Server',\n",
       " 'ODBC Driver 17 for SQL Server',\n",
       " 'MySQL ODBC 8.0 Driver']"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pyodbc\n",
    "pyodbc.drivers()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "HOST = os.getenv('HOST')\n",
    "USER = os.getenv('USERDB')\n",
    "PASS = os.getenv('PASSDB_LOCAL')\n",
    "DB = os.getenv('DATABASE')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import create_engine\n",
    "from sqlalchemy.orm import scoped_session, sessionmaker\n",
    "from sqlalchemy.ext.declarative import declarative_base\n",
    "\n",
    "def set_data(df_mp):\n",
    "\n",
    "    ENGINE = create_engine(\n",
    "        f\"mysql://{USER}:{PASS}@{HOST}/{DB}\"\n",
    "    )\n",
    "    print(f\"mysql://{USER}:{PASS}@{HOST}/{DB}?ssl_mode=VERIFY_IDENTITY\")\n",
    "    session = scoped_session(sessionmaker(bind=ENGINE))\n",
    "\n",
    "    Base = declarative_base()\n",
    "    Base.query = session.query_property()\n",
    "\n",
    "    with ENGINE.connect().execution_options(autocommit=True) as conn:\n",
    "        df_mp.to_sql('rastreo_satelital', con=conn, if_exists='append', index= False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "mysql://root:JB5LEd6r9Pu4ZWa9YC3sSVc@35.239.212.126:3306/rastreosatelital?ssl_mode=VERIFY_IDENTITY\n",
      "CPU times: user 25.7 ms, sys: 781 µs, total: 26.5 ms\n",
      "Wall time: 32.5 ms\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "ENGINE = create_engine(\n",
    "        f\"mysql://{USER}:{PASS}@{HOST}/{DB}\"\n",
    "    )\n",
    "print(f\"mysql://{USER}:{PASS}@{HOST}/{DB}?ssl_mode=VERIFY_IDENTITY\")\n",
    "session = scoped_session(sessionmaker(bind=ENGINE))\n",
    "\n",
    "Base = declarative_base()\n",
    "Base.query = session.query_property()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "InterfaceError",
     "evalue": "(MySQLdb._exceptions.InterfaceError) (0, '')\n(Background on this error at: https://sqlalche.me/e/14/rvf5)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1817'>1818</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1818'>1819</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1819'>1820</a>\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1820'>1821</a>\u001b[0m         )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1822'>1823</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=730'>731</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=731'>732</a>\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py:206\u001b[0m, in \u001b[0;36mBaseCursor.execute\u001b[0;34m(self, query, args)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=204'>205</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(query, (\u001b[39mbytes\u001b[39m, \u001b[39mbytearray\u001b[39m))\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=205'>206</a>\u001b[0m res \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_query(query)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=206'>207</a>\u001b[0m \u001b[39mreturn\u001b[39;00m res\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py:319\u001b[0m, in \u001b[0;36mBaseCursor._query\u001b[0;34m(self, q)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=317'>318</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_result \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=318'>319</a>\u001b[0m db\u001b[39m.\u001b[39;49mquery(q)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/cursors.py?line=319'>320</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_do_get_result(db)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/connections.py:254\u001b[0m, in \u001b[0;36mConnection.query\u001b[0;34m(self, query)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/connections.py?line=252'>253</a>\u001b[0m     query \u001b[39m=\u001b[39m \u001b[39mbytes\u001b[39m(query)\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/MySQLdb/connections.py?line=253'>254</a>\u001b[0m _mysql\u001b[39m.\u001b[39;49mconnection\u001b[39m.\u001b[39;49mquery(\u001b[39mself\u001b[39;49m, query)\n",
      "\u001b[0;31mOperationalError\u001b[0m: (1153, \"Got a packet bigger than 'max_allowed_packet' bytes\")",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mInterfaceError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:983\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=981'>982</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_rollback(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:682\u001b[0m, in \u001b[0;36mDefaultDialect.do_rollback\u001b[0;34m(self, dbapi_connection)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=680'>681</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_rollback\u001b[39m(\u001b[39mself\u001b[39m, dbapi_connection):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=681'>682</a>\u001b[0m     dbapi_connection\u001b[39m.\u001b[39;49mrollback()\n",
      "\u001b[0;31mInterfaceError\u001b[0m: (0, '')",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mInterfaceError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[0;32m<timed exec>:2\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py:2951\u001b[0m, in \u001b[0;36mNDFrame.to_sql\u001b[0;34m(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2793'>2794</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2794'>2795</a>\u001b[0m \u001b[39mWrite records stored in a DataFrame to a SQL database.\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2795'>2796</a>\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2946'>2947</a>\u001b[0m \u001b[39m[(1,), (None,), (2,)]\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2947'>2948</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m  \u001b[39m# noqa:E501\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2948'>2949</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpandas\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mio\u001b[39;00m \u001b[39mimport\u001b[39;00m sql\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2950'>2951</a>\u001b[0m \u001b[39mreturn\u001b[39;00m sql\u001b[39m.\u001b[39;49mto_sql(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2951'>2952</a>\u001b[0m     \u001b[39mself\u001b[39;49m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2952'>2953</a>\u001b[0m     name,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2953'>2954</a>\u001b[0m     con,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2954'>2955</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2955'>2956</a>\u001b[0m     if_exists\u001b[39m=\u001b[39;49mif_exists,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2956'>2957</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2957'>2958</a>\u001b[0m     index_label\u001b[39m=\u001b[39;49mindex_label,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2958'>2959</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2959'>2960</a>\u001b[0m     dtype\u001b[39m=\u001b[39;49mdtype,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2960'>2961</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2961'>2962</a>\u001b[0m )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:697\u001b[0m, in \u001b[0;36mto_sql\u001b[0;34m(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method, engine, **engine_kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=691'>692</a>\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(frame, DataFrame):\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=692'>693</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mNotImplementedError\u001b[39;00m(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=693'>694</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m'\u001b[39m\u001b[39mframe\u001b[39m\u001b[39m'\u001b[39m\u001b[39m argument should be either a Series or a DataFrame\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=694'>695</a>\u001b[0m     )\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=696'>697</a>\u001b[0m \u001b[39mreturn\u001b[39;00m pandas_sql\u001b[39m.\u001b[39;49mto_sql(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=697'>698</a>\u001b[0m     frame,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=698'>699</a>\u001b[0m     name,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=699'>700</a>\u001b[0m     if_exists\u001b[39m=\u001b[39;49mif_exists,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=700'>701</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=701'>702</a>\u001b[0m     index_label\u001b[39m=\u001b[39;49mindex_label,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=702'>703</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=703'>704</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=704'>705</a>\u001b[0m     dtype\u001b[39m=\u001b[39;49mdtype,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=705'>706</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=706'>707</a>\u001b[0m     engine\u001b[39m=\u001b[39;49mengine,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=707'>708</a>\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mengine_kwargs,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=708'>709</a>\u001b[0m )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1739\u001b[0m, in \u001b[0;36mSQLDatabase.to_sql\u001b[0;34m(self, frame, name, if_exists, index, index_label, schema, chunksize, dtype, method, engine, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1726'>1727</a>\u001b[0m sql_engine \u001b[39m=\u001b[39m get_engine(engine)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1728'>1729</a>\u001b[0m table \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mprep_table(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1729'>1730</a>\u001b[0m     frame\u001b[39m=\u001b[39mframe,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1730'>1731</a>\u001b[0m     name\u001b[39m=\u001b[39mname,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1735'>1736</a>\u001b[0m     dtype\u001b[39m=\u001b[39mdtype,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1736'>1737</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1738'>1739</a>\u001b[0m total_inserted \u001b[39m=\u001b[39m sql_engine\u001b[39m.\u001b[39;49minsert_records(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1739'>1740</a>\u001b[0m     table\u001b[39m=\u001b[39;49mtable,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1740'>1741</a>\u001b[0m     con\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnectable,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1741'>1742</a>\u001b[0m     frame\u001b[39m=\u001b[39;49mframe,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1742'>1743</a>\u001b[0m     name\u001b[39m=\u001b[39;49mname,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1743'>1744</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1744'>1745</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1745'>1746</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1746'>1747</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1747'>1748</a>\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mengine_kwargs,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1748'>1749</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1750'>1751</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcheck_case_sensitive(name\u001b[39m=\u001b[39mname, schema\u001b[39m=\u001b[39mschema)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1751'>1752</a>\u001b[0m \u001b[39mreturn\u001b[39;00m total_inserted\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1332\u001b[0m, in \u001b[0;36mSQLAlchemyEngine.insert_records\u001b[0;34m(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1329'>1330</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39minf cannot be used with MySQL\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1330'>1331</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1331'>1332</a>\u001b[0m     \u001b[39mraise\u001b[39;00m err\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1322\u001b[0m, in \u001b[0;36mSQLAlchemyEngine.insert_records\u001b[0;34m(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1318'>1319</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39msqlalchemy\u001b[39;00m \u001b[39mimport\u001b[39;00m exc\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1320'>1321</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1321'>1322</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m table\u001b[39m.\u001b[39;49minsert(chunksize\u001b[39m=\u001b[39;49mchunksize, method\u001b[39m=\u001b[39;49mmethod)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1322'>1323</a>\u001b[0m \u001b[39mexcept\u001b[39;00m exc\u001b[39m.\u001b[39mSQLAlchemyError \u001b[39mas\u001b[39;00m err:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1323'>1324</a>\u001b[0m     \u001b[39m# GH34431\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1324'>1325</a>\u001b[0m     \u001b[39m# https://stackoverflow.com/a/67358288/6067848\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1325'>1326</a>\u001b[0m     msg \u001b[39m=\u001b[39m \u001b[39mr\u001b[39m\u001b[39m\"\"\"\u001b[39m\u001b[39m(\u001b[39m\u001b[39m\\\u001b[39m\u001b[39m(1054, \u001b[39m\u001b[39m\"\u001b[39m\u001b[39mUnknown column \u001b[39m\u001b[39m'\u001b[39m\u001b[39minf(e0)?\u001b[39m\u001b[39m'\u001b[39m\u001b[39m in \u001b[39m\u001b[39m'\u001b[39m\u001b[39mfield list\u001b[39m\u001b[39m'\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\\u001b[39m\u001b[39m))(?#\u001b[39m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1326'>1327</a>\u001b[0m \u001b[39m    )|inf can not be used with MySQL\u001b[39m\u001b[39m\"\"\"\u001b[39m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:950\u001b[0m, in \u001b[0;36mSQLTable.insert\u001b[0;34m(self, chunksize, method)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=946'>947</a>\u001b[0m     \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=948'>949</a>\u001b[0m chunk_iter \u001b[39m=\u001b[39m \u001b[39mzip\u001b[39m(\u001b[39m*\u001b[39m(arr[start_i:end_i] \u001b[39mfor\u001b[39;00m arr \u001b[39min\u001b[39;00m data_list))\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=949'>950</a>\u001b[0m num_inserted \u001b[39m=\u001b[39m exec_insert(conn, keys, chunk_iter)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=950'>951</a>\u001b[0m \u001b[39mif\u001b[39;00m num_inserted \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=951'>952</a>\u001b[0m     total_inserted \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:873\u001b[0m, in \u001b[0;36mSQLTable._execute_insert_multi\u001b[0;34m(self, conn, keys, data_iter)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=870'>871</a>\u001b[0m data \u001b[39m=\u001b[39m [\u001b[39mdict\u001b[39m(\u001b[39mzip\u001b[39m(keys, row)) \u001b[39mfor\u001b[39;00m row \u001b[39min\u001b[39;00m data_iter]\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=871'>872</a>\u001b[0m stmt \u001b[39m=\u001b[39m insert(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtable)\u001b[39m.\u001b[39mvalues(data)\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=872'>873</a>\u001b[0m result \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49mexecute(stmt)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=873'>874</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\u001b[39m.\u001b[39mrowcount\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1306\u001b[0m, in \u001b[0;36mConnection.execute\u001b[0;34m(self, statement, *multiparams, **params)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1301'>1302</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1302'>1303</a>\u001b[0m         exc\u001b[39m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[39m=\u001b[39merr\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1303'>1304</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1304'>1305</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1305'>1306</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m meth(\u001b[39mself\u001b[39;49m, multiparams, params, _EMPTY_EXECUTION_OPTS)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:325\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=320'>321</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_on_connection\u001b[39m(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=321'>322</a>\u001b[0m     \u001b[39mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=322'>323</a>\u001b[0m ):\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=323'>324</a>\u001b[0m     \u001b[39mif\u001b[39;00m _force \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msupports_execution:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=324'>325</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39;49m_execute_clauseelement(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=325'>326</a>\u001b[0m             \u001b[39mself\u001b[39;49m, multiparams, params, execution_options\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=326'>327</a>\u001b[0m         )\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=327'>328</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=328'>329</a>\u001b[0m         \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mObjectNotExecutableError(\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1498\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1485'>1486</a>\u001b[0m compiled_cache \u001b[39m=\u001b[39m execution_options\u001b[39m.\u001b[39mget(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1486'>1487</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mcompiled_cache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_compiled_cache\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1487'>1488</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1489'>1490</a>\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[39m=\u001b[39m elem\u001b[39m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1490'>1491</a>\u001b[0m     dialect\u001b[39m=\u001b[39mdialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1491'>1492</a>\u001b[0m     compiled_cache\u001b[39m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1495'>1496</a>\u001b[0m     linting\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mcompiler_linting \u001b[39m|\u001b[39m compiler\u001b[39m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1496'>1497</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1497'>1498</a>\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1498'>1499</a>\u001b[0m     dialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1499'>1500</a>\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_compiled,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1500'>1501</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1501'>1502</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1502'>1503</a>\u001b[0m     execution_options,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1503'>1504</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1504'>1505</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1505'>1506</a>\u001b[0m     elem,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1506'>1507</a>\u001b[0m     extracted_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1507'>1508</a>\u001b[0m     cache_hit\u001b[39m=\u001b[39;49mcache_hit,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1508'>1509</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1509'>1510</a>\u001b[0m \u001b[39mif\u001b[39;00m has_events:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1510'>1511</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1511'>1512</a>\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1512'>1513</a>\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1516'>1517</a>\u001b[0m         ret,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1517'>1518</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1862\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1858'>1859</a>\u001b[0m             branched\u001b[39m.\u001b[39mclose()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1860'>1861</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1861'>1862</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1862'>1863</a>\u001b[0m         e, statement, parameters, cursor, context\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1863'>1864</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1865'>1866</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2038\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2035'>2036</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_safe_close_cursor(cursor)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2036'>2037</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise(warn_only\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m):\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2037'>2038</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2039'>2040</a>\u001b[0m \u001b[39mif\u001b[39;00m newraise:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2040'>2041</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:84\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[0;34m(self, type_, value, traceback)\u001b[0m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=77'>78</a>\u001b[0m     warn(\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=78'>79</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mAn exception has occurred during handling of a \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=79'>80</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mprevious exception.  The previous exception \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=80'>81</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mis:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m0\u001b[39m], \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m])\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=81'>82</a>\u001b[0m     )\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=82'>83</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m---> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=83'>84</a>\u001b[0m compat\u001b[39m.\u001b[39;49mraise_(value, with_traceback\u001b[39m=\u001b[39;49mtraceback)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2038\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2035'>2036</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_safe_close_cursor(cursor)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2036'>2037</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise(warn_only\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m):\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2037'>2038</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2039'>2040</a>\u001b[0m \u001b[39mif\u001b[39;00m newraise:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2040'>2041</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1113\u001b[0m, in \u001b[0;36mConnection._autorollback\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1109'>1110</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__branch_from\u001b[39m.\u001b[39m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1111'>1112</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39min_transaction():\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1112'>1113</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_rollback_impl()\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:985\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mdo_rollback(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=984'>985</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(e, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1945\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1941'>1942</a>\u001b[0m invalidate_pool_on_disconnect \u001b[39m=\u001b[39m \u001b[39mnot\u001b[39;00m is_exit_exception\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1943'>1944</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reentrant_error:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1944'>1945</a>\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1945'>1946</a>\u001b[0m         exc\u001b[39m.\u001b[39;49mDBAPIError\u001b[39m.\u001b[39;49minstance(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1946'>1947</a>\u001b[0m             statement,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1947'>1948</a>\u001b[0m             parameters,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1948'>1949</a>\u001b[0m             e,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1949'>1950</a>\u001b[0m             \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdbapi\u001b[39m.\u001b[39;49mError,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1950'>1951</a>\u001b[0m             hide_parameters\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mhide_parameters,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1951'>1952</a>\u001b[0m             dialect\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1952'>1953</a>\u001b[0m             ismulti\u001b[39m=\u001b[39;49mcontext\u001b[39m.\u001b[39;49mexecutemany\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1953'>1954</a>\u001b[0m             \u001b[39mif\u001b[39;49;00m context \u001b[39mis\u001b[39;49;00m \u001b[39mnot\u001b[39;49;00m \u001b[39mNone\u001b[39;49;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1954'>1955</a>\u001b[0m             \u001b[39melse\u001b[39;49;00m \u001b[39mNone\u001b[39;49;00m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1955'>1956</a>\u001b[0m         ),\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1956'>1957</a>\u001b[0m         with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m],\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1957'>1958</a>\u001b[0m         from_\u001b[39m=\u001b[39;49me,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1958'>1959</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1959'>1960</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reentrant_error \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1960'>1961</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1961'>1962</a>\u001b[0m     \u001b[39m# non-DBAPI error - if we already got a context,\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1962'>1963</a>\u001b[0m     \u001b[39m# or there's no string statement, don't wrap it\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:983\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=980'>981</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_log_info(\u001b[39m\"\u001b[39m\u001b[39mROLLBACK\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=981'>982</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_rollback(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=984'>985</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_handle_dbapi_exception(e, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:682\u001b[0m, in \u001b[0;36mDefaultDialect.do_rollback\u001b[0;34m(self, dbapi_connection)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=680'>681</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_rollback\u001b[39m(\u001b[39mself\u001b[39m, dbapi_connection):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=681'>682</a>\u001b[0m     dbapi_connection\u001b[39m.\u001b[39;49mrollback()\n",
      "\u001b[0;31mInterfaceError\u001b[0m: (MySQLdb._exceptions.InterfaceError) (0, '')\n(Background on this error at: https://sqlalche.me/e/14/rvf5)"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "with ENGINE.connect().execution_options(autocommit=True) as conn:\n",
    "        df.to_sql('rastreo_satelital_v2', con=conn, if_exists='append', index= False, method='multi')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import urllib\n",
    "from sqlalchemy import create_engine\n",
    "HOST = os.getenv('HOST')\n",
    "USER = os.getenv('USERDB')\n",
    "PASS = os.getenv('PASSDB_LOCAL')\n",
    "DB = os.getenv('DATABASE')\n",
    "\n",
    "connection_string = (\n",
    "    f'DRIVER=MySQL ODBC 8.0 Driver;'\n",
    "    f'SERVER=35.239.212.126;'\n",
    "    f'DATABASE={DB};'\n",
    "    f'UID={USER};'\n",
    "    f'PWD={PASS};'\n",
    ")\n",
    "params = urllib.parse.quote_plus(connection_string)\n",
    "engine = create_engine(\"mysql+pyodbc:///?odbc_connect={}\".format(params))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<sqlalchemy.engine.base.Connection at 0x7fc7163cc9a0>"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import event\n",
    "\n",
    "\n",
    "@event.listens_for(engine, \"before_cursor_execute\")\n",
    "def receive_before_cursor_execute(\n",
    "    conn, cursor, statement, params, context, executemany\n",
    "):\n",
    "    if executemany:\n",
    "        cursor.fast_executemany = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1819, in _execute_context\n",
      "    self.dialect.do_execute(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 732, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "pyodbc.Error: ('HY000', \"[HY000] [MySQL][ODBC 8.0(w) Driver][mysqld-8.0.26-google]Got a packet bigger than 'max_allowed_packet' bytes (1153) (SQLPrepare)\")\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 983, in _rollback_impl\n",
      "    self.engine.dialect.do_rollback(self.connection)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "pyodbc.Error: ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<timed exec>\", line 2, in <module>\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py\", line 2951, in to_sql\n",
      "    return sql.to_sql(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 697, in to_sql\n",
      "    return pandas_sql.to_sql(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 1739, in to_sql\n",
      "    total_inserted = sql_engine.insert_records(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 1332, in insert_records\n",
      "    raise err\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 1322, in insert_records\n",
      "    return table.insert(chunksize=chunksize, method=method)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 950, in insert\n",
      "    num_inserted = exec_insert(conn, keys, chunk_iter)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py\", line 873, in _execute_insert_multi\n",
      "    result = conn.execute(stmt)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1306, in execute\n",
      "    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py\", line 325, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1498, in _execute_clauseelement\n",
      "    ret = self._execute_context(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1862, in _execute_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 2038, in _handle_dbapi_exception\n",
      "    self._autorollback()\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py\", line 84, in __exit__\n",
      "    compat.raise_(value, with_traceback=traceback)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n",
      "    raise exception\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 2038, in _handle_dbapi_exception\n",
      "    self._autorollback()\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1113, in _autorollback\n",
      "    self._rollback_impl()\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 985, in _rollback_impl\n",
      "    self._handle_dbapi_exception(e, None, None, None, None)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1945, in _handle_dbapi_exception\n",
      "    util.raise_(\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n",
      "    raise exception\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 983, in _rollback_impl\n",
      "    self.engine.dialect.do_rollback(self.connection)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')\n",
      "(Background on this error at: https://sqlalche.me/e/14/dbapi)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "pyodbc.Error: ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')\n"
     ]
    },
    {
     "ename": "DBAPIError",
     "evalue": "(pyodbc.Error) ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')\n(Background on this error at: https://sqlalche.me/e/14/dbapi)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mError\u001b[0m                                     Traceback (most recent call last)",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1817'>1818</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1818'>1819</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1819'>1820</a>\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1820'>1821</a>\u001b[0m         )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1822'>1823</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=730'>731</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=731'>732</a>\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[0;31mError\u001b[0m: ('HY000', \"[HY000] [MySQL][ODBC 8.0(w) Driver][mysqld-8.0.26-google]Got a packet bigger than 'max_allowed_packet' bytes (1153) (SQLPrepare)\")",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mError\u001b[0m                                     Traceback (most recent call last)",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:983\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=981'>982</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_rollback(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:682\u001b[0m, in \u001b[0;36mDefaultDialect.do_rollback\u001b[0;34m(self, dbapi_connection)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=680'>681</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_rollback\u001b[39m(\u001b[39mself\u001b[39m, dbapi_connection):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=681'>682</a>\u001b[0m     dbapi_connection\u001b[39m.\u001b[39;49mrollback()\n",
      "\u001b[0;31mError\u001b[0m: ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mDBAPIError\u001b[0m                                Traceback (most recent call last)",
      "File \u001b[0;32m<timed exec>:2\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py:2951\u001b[0m, in \u001b[0;36mNDFrame.to_sql\u001b[0;34m(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2793'>2794</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2794'>2795</a>\u001b[0m \u001b[39mWrite records stored in a DataFrame to a SQL database.\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2795'>2796</a>\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2946'>2947</a>\u001b[0m \u001b[39m[(1,), (None,), (2,)]\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2947'>2948</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m  \u001b[39m# noqa:E501\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2948'>2949</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpandas\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mio\u001b[39;00m \u001b[39mimport\u001b[39;00m sql\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2950'>2951</a>\u001b[0m \u001b[39mreturn\u001b[39;00m sql\u001b[39m.\u001b[39;49mto_sql(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2951'>2952</a>\u001b[0m     \u001b[39mself\u001b[39;49m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2952'>2953</a>\u001b[0m     name,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2953'>2954</a>\u001b[0m     con,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2954'>2955</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2955'>2956</a>\u001b[0m     if_exists\u001b[39m=\u001b[39;49mif_exists,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2956'>2957</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2957'>2958</a>\u001b[0m     index_label\u001b[39m=\u001b[39;49mindex_label,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2958'>2959</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2959'>2960</a>\u001b[0m     dtype\u001b[39m=\u001b[39;49mdtype,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2960'>2961</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/core/generic.py?line=2961'>2962</a>\u001b[0m )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:697\u001b[0m, in \u001b[0;36mto_sql\u001b[0;34m(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method, engine, **engine_kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=691'>692</a>\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(frame, DataFrame):\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=692'>693</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mNotImplementedError\u001b[39;00m(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=693'>694</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m'\u001b[39m\u001b[39mframe\u001b[39m\u001b[39m'\u001b[39m\u001b[39m argument should be either a Series or a DataFrame\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=694'>695</a>\u001b[0m     )\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=696'>697</a>\u001b[0m \u001b[39mreturn\u001b[39;00m pandas_sql\u001b[39m.\u001b[39;49mto_sql(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=697'>698</a>\u001b[0m     frame,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=698'>699</a>\u001b[0m     name,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=699'>700</a>\u001b[0m     if_exists\u001b[39m=\u001b[39;49mif_exists,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=700'>701</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=701'>702</a>\u001b[0m     index_label\u001b[39m=\u001b[39;49mindex_label,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=702'>703</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=703'>704</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=704'>705</a>\u001b[0m     dtype\u001b[39m=\u001b[39;49mdtype,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=705'>706</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=706'>707</a>\u001b[0m     engine\u001b[39m=\u001b[39;49mengine,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=707'>708</a>\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mengine_kwargs,\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=708'>709</a>\u001b[0m )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1739\u001b[0m, in \u001b[0;36mSQLDatabase.to_sql\u001b[0;34m(self, frame, name, if_exists, index, index_label, schema, chunksize, dtype, method, engine, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1726'>1727</a>\u001b[0m sql_engine \u001b[39m=\u001b[39m get_engine(engine)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1728'>1729</a>\u001b[0m table \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mprep_table(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1729'>1730</a>\u001b[0m     frame\u001b[39m=\u001b[39mframe,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1730'>1731</a>\u001b[0m     name\u001b[39m=\u001b[39mname,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1735'>1736</a>\u001b[0m     dtype\u001b[39m=\u001b[39mdtype,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1736'>1737</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1738'>1739</a>\u001b[0m total_inserted \u001b[39m=\u001b[39m sql_engine\u001b[39m.\u001b[39;49minsert_records(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1739'>1740</a>\u001b[0m     table\u001b[39m=\u001b[39;49mtable,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1740'>1741</a>\u001b[0m     con\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnectable,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1741'>1742</a>\u001b[0m     frame\u001b[39m=\u001b[39;49mframe,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1742'>1743</a>\u001b[0m     name\u001b[39m=\u001b[39;49mname,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1743'>1744</a>\u001b[0m     index\u001b[39m=\u001b[39;49mindex,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1744'>1745</a>\u001b[0m     schema\u001b[39m=\u001b[39;49mschema,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1745'>1746</a>\u001b[0m     chunksize\u001b[39m=\u001b[39;49mchunksize,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1746'>1747</a>\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1747'>1748</a>\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mengine_kwargs,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1748'>1749</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1750'>1751</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcheck_case_sensitive(name\u001b[39m=\u001b[39mname, schema\u001b[39m=\u001b[39mschema)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1751'>1752</a>\u001b[0m \u001b[39mreturn\u001b[39;00m total_inserted\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1332\u001b[0m, in \u001b[0;36mSQLAlchemyEngine.insert_records\u001b[0;34m(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1329'>1330</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39minf cannot be used with MySQL\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1330'>1331</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1331'>1332</a>\u001b[0m     \u001b[39mraise\u001b[39;00m err\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:1322\u001b[0m, in \u001b[0;36mSQLAlchemyEngine.insert_records\u001b[0;34m(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1318'>1319</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39msqlalchemy\u001b[39;00m \u001b[39mimport\u001b[39;00m exc\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1320'>1321</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1321'>1322</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m table\u001b[39m.\u001b[39;49minsert(chunksize\u001b[39m=\u001b[39;49mchunksize, method\u001b[39m=\u001b[39;49mmethod)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1322'>1323</a>\u001b[0m \u001b[39mexcept\u001b[39;00m exc\u001b[39m.\u001b[39mSQLAlchemyError \u001b[39mas\u001b[39;00m err:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1323'>1324</a>\u001b[0m     \u001b[39m# GH34431\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1324'>1325</a>\u001b[0m     \u001b[39m# https://stackoverflow.com/a/67358288/6067848\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1325'>1326</a>\u001b[0m     msg \u001b[39m=\u001b[39m \u001b[39mr\u001b[39m\u001b[39m\"\"\"\u001b[39m\u001b[39m(\u001b[39m\u001b[39m\\\u001b[39m\u001b[39m(1054, \u001b[39m\u001b[39m\"\u001b[39m\u001b[39mUnknown column \u001b[39m\u001b[39m'\u001b[39m\u001b[39minf(e0)?\u001b[39m\u001b[39m'\u001b[39m\u001b[39m in \u001b[39m\u001b[39m'\u001b[39m\u001b[39mfield list\u001b[39m\u001b[39m'\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\\u001b[39m\u001b[39m))(?#\u001b[39m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=1326'>1327</a>\u001b[0m \u001b[39m    )|inf can not be used with MySQL\u001b[39m\u001b[39m\"\"\"\u001b[39m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:950\u001b[0m, in \u001b[0;36mSQLTable.insert\u001b[0;34m(self, chunksize, method)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=946'>947</a>\u001b[0m     \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=948'>949</a>\u001b[0m chunk_iter \u001b[39m=\u001b[39m \u001b[39mzip\u001b[39m(\u001b[39m*\u001b[39m(arr[start_i:end_i] \u001b[39mfor\u001b[39;00m arr \u001b[39min\u001b[39;00m data_list))\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=949'>950</a>\u001b[0m num_inserted \u001b[39m=\u001b[39m exec_insert(conn, keys, chunk_iter)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=950'>951</a>\u001b[0m \u001b[39mif\u001b[39;00m num_inserted \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=951'>952</a>\u001b[0m     total_inserted \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py:873\u001b[0m, in \u001b[0;36mSQLTable._execute_insert_multi\u001b[0;34m(self, conn, keys, data_iter)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=870'>871</a>\u001b[0m data \u001b[39m=\u001b[39m [\u001b[39mdict\u001b[39m(\u001b[39mzip\u001b[39m(keys, row)) \u001b[39mfor\u001b[39;00m row \u001b[39min\u001b[39;00m data_iter]\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=871'>872</a>\u001b[0m stmt \u001b[39m=\u001b[39m insert(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtable)\u001b[39m.\u001b[39mvalues(data)\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=872'>873</a>\u001b[0m result \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49mexecute(stmt)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/pandas/io/sql.py?line=873'>874</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\u001b[39m.\u001b[39mrowcount\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1306\u001b[0m, in \u001b[0;36mConnection.execute\u001b[0;34m(self, statement, *multiparams, **params)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1301'>1302</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1302'>1303</a>\u001b[0m         exc\u001b[39m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[39m=\u001b[39merr\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1303'>1304</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1304'>1305</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1305'>1306</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m meth(\u001b[39mself\u001b[39;49m, multiparams, params, _EMPTY_EXECUTION_OPTS)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:325\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=320'>321</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_on_connection\u001b[39m(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=321'>322</a>\u001b[0m     \u001b[39mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=322'>323</a>\u001b[0m ):\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=323'>324</a>\u001b[0m     \u001b[39mif\u001b[39;00m _force \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msupports_execution:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=324'>325</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39;49m_execute_clauseelement(\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=325'>326</a>\u001b[0m             \u001b[39mself\u001b[39;49m, multiparams, params, execution_options\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=326'>327</a>\u001b[0m         )\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=327'>328</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=328'>329</a>\u001b[0m         \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mObjectNotExecutableError(\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1498\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1485'>1486</a>\u001b[0m compiled_cache \u001b[39m=\u001b[39m execution_options\u001b[39m.\u001b[39mget(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1486'>1487</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mcompiled_cache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_compiled_cache\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1487'>1488</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1489'>1490</a>\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[39m=\u001b[39m elem\u001b[39m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1490'>1491</a>\u001b[0m     dialect\u001b[39m=\u001b[39mdialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1491'>1492</a>\u001b[0m     compiled_cache\u001b[39m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1495'>1496</a>\u001b[0m     linting\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mcompiler_linting \u001b[39m|\u001b[39m compiler\u001b[39m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1496'>1497</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1497'>1498</a>\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1498'>1499</a>\u001b[0m     dialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1499'>1500</a>\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_compiled,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1500'>1501</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1501'>1502</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1502'>1503</a>\u001b[0m     execution_options,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1503'>1504</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1504'>1505</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1505'>1506</a>\u001b[0m     elem,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1506'>1507</a>\u001b[0m     extracted_params,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1507'>1508</a>\u001b[0m     cache_hit\u001b[39m=\u001b[39;49mcache_hit,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1508'>1509</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1509'>1510</a>\u001b[0m \u001b[39mif\u001b[39;00m has_events:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1510'>1511</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1511'>1512</a>\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1512'>1513</a>\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1516'>1517</a>\u001b[0m         ret,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1517'>1518</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1862\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1858'>1859</a>\u001b[0m             branched\u001b[39m.\u001b[39mclose()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1860'>1861</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1861'>1862</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1862'>1863</a>\u001b[0m         e, statement, parameters, cursor, context\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1863'>1864</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1865'>1866</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2038\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2035'>2036</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_safe_close_cursor(cursor)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2036'>2037</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise(warn_only\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m):\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2037'>2038</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2039'>2040</a>\u001b[0m \u001b[39mif\u001b[39;00m newraise:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2040'>2041</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:84\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[0;34m(self, type_, value, traceback)\u001b[0m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=77'>78</a>\u001b[0m     warn(\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=78'>79</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mAn exception has occurred during handling of a \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=79'>80</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mprevious exception.  The previous exception \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=80'>81</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mis:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m0\u001b[39m], \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m])\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=81'>82</a>\u001b[0m     )\n\u001b[1;32m     <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=82'>83</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m---> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=83'>84</a>\u001b[0m compat\u001b[39m.\u001b[39;49mraise_(value, with_traceback\u001b[39m=\u001b[39;49mtraceback)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2038\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2035'>2036</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_safe_close_cursor(cursor)\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2036'>2037</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise(warn_only\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m):\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2037'>2038</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2039'>2040</a>\u001b[0m \u001b[39mif\u001b[39;00m newraise:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2040'>2041</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1113\u001b[0m, in \u001b[0;36mConnection._autorollback\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1109'>1110</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__branch_from\u001b[39m.\u001b[39m_autorollback()\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1111'>1112</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39min_transaction():\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1112'>1113</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_rollback_impl()\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:985\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mdo_rollback(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=984'>985</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(e, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m, \u001b[39mNone\u001b[39;49;00m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1945\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1941'>1942</a>\u001b[0m invalidate_pool_on_disconnect \u001b[39m=\u001b[39m \u001b[39mnot\u001b[39;00m is_exit_exception\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1943'>1944</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reentrant_error:\n\u001b[0;32m-> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1944'>1945</a>\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1945'>1946</a>\u001b[0m         exc\u001b[39m.\u001b[39;49mDBAPIError\u001b[39m.\u001b[39;49minstance(\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1946'>1947</a>\u001b[0m             statement,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1947'>1948</a>\u001b[0m             parameters,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1948'>1949</a>\u001b[0m             e,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1949'>1950</a>\u001b[0m             \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdbapi\u001b[39m.\u001b[39;49mError,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1950'>1951</a>\u001b[0m             hide_parameters\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mhide_parameters,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1951'>1952</a>\u001b[0m             dialect\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1952'>1953</a>\u001b[0m             ismulti\u001b[39m=\u001b[39;49mcontext\u001b[39m.\u001b[39;49mexecutemany\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1953'>1954</a>\u001b[0m             \u001b[39mif\u001b[39;49;00m context \u001b[39mis\u001b[39;49;00m \u001b[39mnot\u001b[39;49;00m \u001b[39mNone\u001b[39;49;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1954'>1955</a>\u001b[0m             \u001b[39melse\u001b[39;49;00m \u001b[39mNone\u001b[39;49;00m,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1955'>1956</a>\u001b[0m         ),\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1956'>1957</a>\u001b[0m         with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m],\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1957'>1958</a>\u001b[0m         from_\u001b[39m=\u001b[39;49me,\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1958'>1959</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1959'>1960</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reentrant_error \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1960'>1961</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1961'>1962</a>\u001b[0m     \u001b[39m# non-DBAPI error - if we already got a context,\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1962'>1963</a>\u001b[0m     \u001b[39m# or there's no string statement, don't wrap it\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:983\u001b[0m, in \u001b[0;36mConnection._rollback_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=980'>981</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_log_info(\u001b[39m\"\u001b[39m\u001b[39mROLLBACK\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=981'>982</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=982'>983</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mengine\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_rollback(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnection)\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=983'>984</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=984'>985</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_handle_dbapi_exception(e, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m, \u001b[39mNone\u001b[39;00m)\n",
      "File \u001b[0;32m~/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:682\u001b[0m, in \u001b[0;36mDefaultDialect.do_rollback\u001b[0;34m(self, dbapi_connection)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=680'>681</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_rollback\u001b[39m(\u001b[39mself\u001b[39m, dbapi_connection):\n\u001b[0;32m--> <a href='file:///home/dmateons/Documents/mateo/python/Parallel_Concurrent/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=681'>682</a>\u001b[0m     dbapi_connection\u001b[39m.\u001b[39;49mrollback()\n",
      "\u001b[0;31mDBAPIError\u001b[0m: (pyodbc.Error) ('HY000', '[HY000] [MySQL][ODBC 8.0(w) Driver] (517) (SQLEndTran)')\n(Background on this error at: https://sqlalche.me/e/14/dbapi)"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "with engine.connect().execution_options(autocommit=True) as conn:\n",
    "        df.to_sql('rastreo_satelital_v2', con=conn, if_exists='append', index= False, method='multi')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "094c2986e07737817cb55fcf5ca42c4eadb8fc0fc8611094c6716c49f9e419fd"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 ('venv': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
